Фрешер Антон
urfu-2017/markup-task-8 pull request #39
Opened 2017-12-04 22:08 UTC by tonyfresher

2017-12-04 22:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-12-04 22:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-12-04 22:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-05 19:26 UTC, msmirnov requested changes
Небольшое замечание есть, в остальном очень круто!
🍅

2017-12-05 19:26 UTC, msmirnov commented on index.css
> +    transform: translate(150px);
Свойство translate должно принимать два аргумента. Здесь можно использовать translateX.

2017-12-05 19:26 UTC, msmirnov commented on index.css
> +        transform: translate(-500px);
translateX

2017-12-06 08:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-06 12:30 UTC, msmirnov approved these changes

2017-12-06 12:30 UTC, closed without merging